name: CMake Workflow

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libcunit1 libcunit1-doc libcunit1-dev cmake valgrind libcriterion-dev
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18 

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Run Formatter
        run: cmake --build build --target format

      - name: Run Linter
        continue-on-error: true
        run: |
          cmake --build build --target lint

      - name: Build Project
        run: cmake --build build

      - name: Run Tests
        run: ctest --output-on-failure --test-dir build

      - name: Run Valgrind
        continue-on-error: true
        run: |
          valgrind --leak-check=full bin/z
